[server]
url = "https://127.0.0.1:50500"
host = "chuni.stellopath.net"
# insecure = true
cert = "cert.der"
# bind = "[::]:0"

[tun]
# Name of the TUN device
name = "concab"
# Local IP address
addr = "192.168.139.11/24"
# Gateway IP address
dest = "192.168.139.1"
# guid = "e1fd7f84-1bda-4459-9f2b-57b861d857a0"
