[server]
url = "https://localhost:50500"
# host = "localhost"
# insecure = true
# cert = "chain.pem"
# bind = "[::]:0"

[tun]
# Name of the TUN device
name = "concab"
# Local IP address
addr = "192.168.139.11/24"
# Gateway IP address
dest = "192.168.139.1"
# Windows only: GUID of the device
# guid = "e1fd7f84-1bda-4459-9f2b-57b861d857a0"
